### PR TITLE
Website use cases

### LINKED ISSUE #4: Create use cases diagram
- [x] Define use cases for website
- [x] Define use cases for drawing app
- [x] Describe use cases
- [x] Describe roles

### PR DESCRIPTION
**Pull request by Almantask**
Refining PR #16 and issue #4 

- [x] Use cases diagram
- [x] Actors refinement
- [x] Cases refinement

### CODE REVIEW

**Comment by Almantask** [comment]
Going to have a look at @RoelofWobben case and actor descriptions tomorrow

**Comment by HellHunterMax** [comment]
I hope you don't mind I worked a bit on this. I was reading it and saw some typo's so i fixed those and while at it "finished" the bottom 3 for review.

**Review by ghost — APPROVED** [review]

**Comment by Almantask** [comment]
> I hope you don't mind I worked a bit on this. I was reading it and saw some typo's so i fixed those and while at it "finished" the bottom 3 for review.

Absolutely no problem, if it didn't cost you too much time.

**Comment by DavidKatona** [comment]
This new use case diagram for the website answered tons of questions for me. I like what you've done. :)

**Review by HellHunterMax — APPROVED** [review]
looks good.

**Comment by Almantask** [comment]
Added two more use cases: 
image

**Pull request merged**
