### PR TITLE
Wireframe for Mobile app Design

### LINKED ISSUE #12: Create mobile app wireframe
- [ ] Drawing window
- [ ] Info & Contacts section
- [ ] Drawing submission window

### PR DESCRIPTION
**Pull request by HellHunterMax**
Not sure if this is the way to go but here is the first iteration for the Mobile Wire Frame.

I think we should focus more on the gallery in stead of the drawing for the mobile app.
anyone can give their view on what they think! Please be honest!

If we want a Gallery too ill ad that page as well.
#12

### CODE REVIEW

**Comment by DavidKatona** [comment]
I couldn't comment right next to the images, so I'm going to do it here.

#Drawing Interface:
I really like what you did with the drawing interface. It looks great and yet simple. I guess the pop-ups would be used to host features like different brushes, color pallettes, eraser tools, etc. right?

#Info Interface:
Well, not much to nitpick on here. First, I wanted to say that the image could be a bit larger, but honestly, that all depends on how much text they want to place on this section describing the project. So, I think it's great.

#Gallery Interface:
I think galleries will be really useful as that would be the ultimate promotion for the website and the project. I'd imagine there to be multiple galleries under that section, something like a "Public Gallery" - one, where everyone could post, and another one "Promotional Gallery" - where only professional, and selected artists could post.

Now, depending on whether we want to have registrations, and user profiles as well (at least for artists), we could add a "Projects" section, or something like that, where artists could create projects of their own, post images, describe their goals with the given project, and give some background information to people who will end up watching their work.

I honestly, don't know how much we want to go into this direction, but I thought I would ask. :)

Anyways, great job, I like what you did! 😄

**Comment by ghost** [comment]
I agree, the wireframes look very good to me

**Comment by HellHunterMax** [comment]
Thank you for the comments up until now. i agree with the gallery. so i added that next.

**Comment by Almantask** [comment]
Had a quick look and yeah! It looks surprisingly good 😄 Well done! Though keep in mind this is just an initial design, for placements. Second iteration will be to add concrete styles. I think our PO (product owner) will need to have a look (on  Monday I guess), to review.

**Comment by HellHunterMax** [comment]
remove Guest from login page.

**Comment by HellHunterMax** [comment]
create admin aputee page

**Comment by HellHunterMax** [comment]
remove remove

**Pull request merged**
